# Generated by Django 3.0.2 on 2020-01-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='website',
            new_name='wechat',
        ),
    ]
