# Generated by Django 3.0.2 on 2020-01-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200125_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='profession',
            new_name='specialty',
        ),
    ]
