# Generated by Django 3.0.2 on 2020-02-03 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='column',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='article', to='article.ArticleColumn'),
        ),
    ]
