# Generated by Django 3.0.2 on 2020-02-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200203_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
    ]
