# Generated by Django 3.0.3 on 2020-02-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_articlepost_showtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='showtype',
            field=models.CharField(choices=[('0', 'DEFAULT'), ('1', 'SPECIAL')], default='0', max_length=10),
        ),
    ]
