# Generated by Django 3.0.3 on 2020-03-15 15:11

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0008_auto_20200213_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepost',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='articlepost',
            name='targetuser',
            field=models.ManyToManyField(blank=True, related_name='dessert', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='showtype',
            field=models.CharField(choices=[('0', '文章'), ('1', '甜品站'), ('2', '特殊页面')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
