# Generated by Django 3.0.3 on 2020-03-16 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0009_auto_20200315_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='body',
            field=models.TextField(verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='column',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='article', to='article.ArticleColumn', verbose_name='栏目'),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='showtype',
            field=models.CharField(choices=[('0', '文章'), ('1', '甜品站'), ('2', '特殊页面')], default='0', max_length=10, verbose_name='展示类型'),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='targetuser',
            field=models.ManyToManyField(blank=True, related_name='dessert', to=settings.AUTH_USER_MODEL, verbose_name='目标用户(甜品站)'),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
    ]
