# Generated by Django 3.0.3 on 2020-03-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20200316_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepost',
            options={'ordering': ('-updated',), 'permissions': (('get_dessert', '可以进入甜品站，查看以自己为对象的文章。'),)},
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='Articles', to='article.ArticleTag', verbose_name='标签'),
        ),
    ]
