# Generated by Django 3.0.3 on 2020-04-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20200321_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='链接名')),
                ('link', models.URLField(verbose_name='链接')),
            ],
        ),
    ]
