# Generated by Django 3.0.3 on 2020-04-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_navlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='navlink',
            name='show',
            field=models.BooleanField(default=True, verbose_name='展示'),
        ),
    ]
