# Generated by Django 3.0.3 on 2020-04-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_navlink_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navlink',
            name='link',
            field=models.CharField(default='/article/', max_length=100, verbose_name='链接'),
        ),
    ]
