# Generated by Django 3.0.3 on 2020-02-13 08:51

from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(blank=True, upload_to=image.models.path_and_rename, verbose_name='图片'),
        ),
    ]
