# Generated by Django 3.0.2 on 2020-01-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxname', models.CharField(max_length=20)),
                ('urls', models.TextField(blank=True)),
                ('created', models.DateField(auto_now=True)),
            ],
        ),
    ]
