# Generated by Django 3.0.3 on 2020-04-11 02:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_linkbox_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkbox',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='linkbox',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
